DATALOADER:
  NUM_WORKERS: 4
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  VGGNETS:
    OUT_FEATURES: ["vgg5"]
    VGG5_DILATION: 2
  RESNETSWS:
    OUT_FEATURES: ["res5"]
    RES5_DILATION: 2
  VIT:
    OUT_FEATURES: ["vit12"]
  RPN:
    IN_FEATURES: ["res5"]
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 4096
    POSITIVE_FRACTION: 1.0
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152)
  MAX_SIZE_TRAIN: 4000
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 4000
  CROP:
    ENABLED: False
SOLVER:
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "norm"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
TEST:
  AUG:
    ENABLED: True
    NAME: "GeneralizedRCNNWithTTAAverage"
    MIN_SIZES: (480, 576, 688, 768, 864, 960, 1056, 1152)
    MAX_SIZE: 4000
    FLIP: True
  VIS:
    ENABLED: False
    SCORE_THRESH: 0.5
VERSION: 2
