_BASE_: "../Base-RCNN-DilatedC5.yaml"
DATASETS:
  TRAIN: ("voc_2007_trainval", )
  PROPOSAL_FILES_TRAIN: ("datasets/proposals/voc_2007_trainval_mcg_proposals_d2.pkl", )
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 4000
  TEST: ("voc_2007_test", )
  PROPOSAL_FILES_TEST: ("datasets/proposals/voc_2007_test_mcg_proposals_d2.pkl", )
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 4000
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (15000, )
  GAMMA: 0.1
  MAX_ITER: 25000  # 40 epochs for voc07
  WARMUP_ITERS: 250
  WARMUP_FACTOR: !!python/object/apply:eval [1.0 / 3.0]
  WARMUP_METHOD: "linear"
  OPTIMIZER_NAME: "SGD"
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0005
  BIAS_LR_FACTOR: 2.0
  WEIGHT_DECAY_BIAS: 0.0
  CHECKPOINT_PERIOD: 2500
TEST:
  EVAL_PERIOD: 2500
  EVAL_TRAIN: True
